name: Auto-merge PRs to main

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto-merge
        run: gh pr merge "${{ github.event.pull_request.number }}" --merge --auto --repo "${{ github.repository }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
